### ISSUE TITLE
Actions Embeds

### ISSUE THREAD

**Issue by dawnofmidnight** [gurkult/gurkbot#127] opened 2021-05-11 13:54 UTC
Currently, the embeds in `#dev-log` aren't very informative. It would be nice to set up Sebastiaan's [fancy actions embeds](https://github.com/marketplace/actions/github-actions-status-embed-for-discord) so that we know which PR succeeded or failed.

This would allow us to go from this: 
![image](https://user-images.githubusercontent.com/78233879/117827196-c6ebf100-b23e-11eb-9b4c-34ca08982e61.png)
to this:
![image](https://user-images.githubusercontent.com/78233879/117827239-ceab9580-b23e-11eb-9dc6-1984dd0d2011.png)

**Comment by Shivansh-007** [comment] 2021-05-16 15:22
Duplicate of #78

**Comment by Akarys42** [comment] 2021-05-20 08:19
Duplicate of #78 as pointed out by Jason.

**Closed by Akarys42** 2021-05-20 08:19 UTC
